version: '3.7'

services:
  
  client:
    container_name: client
    restart: always
    build:
      context: ./client
    volumes:
      - './client:/client'
      - '/client/node_modules'
    ports:
      - 3000:3000
    links:
      - api

  api:
    container_name: api
    build:
      context: ./api
    restart: always
    ports:
        - "5000:5000"
    volumes:
        - ./api:/api
        - /api/node_modules
    depends_on:
        - mongodb
        - redis

  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
        - ./.docker/mongodb:/data/db
    ports:
        - 27017:27017
    command: mongod --noauth

  redis:
      image: "redis:alpine"
      container_name: redis
      hostname: redis
      ports:
        - "6379:6379"
      command: redis-server --appendonly yes
      volumes:
        - ./.docker/redis:/data